language: d
sudo: false
addons:
  apt:
    packages:
    - libevent-dev
    - libssl-dev
d:
  - dmd
  - ldc

env:
 - VIBED_SSL=openssl
 - VIBED_SSL=botan

# Data definition directives inside inline asm are not supported yet.
matrix:
  allow_failures:
      - d: ldc
        env: VIBED_SSL=botan

script: dub test --override-config="vibe-d:tls/${VIBED_SSL}"
